---
title: "Variables"

date: 2026/03/12
date-format: long

lang: es
execute: 
  echo: false

tbl-colwidths: [30, 70]

toc: true
toc-title: Contenido
number-sections: true
number-depth: 3

format: 
  html:
    embed-resources: true
    theme: cosmo
    html-math-method: katex
  pdf:
    papersize: a4
    documentclass: article
    colorlinks: true
    pdf-engine: lualatex
    mainfont: Alegreya
    sansfont: Roboto
    monofont: "Fira Code"

editor: visual
---

## Fuentes

Los datos provienen de:

-   Encuesta Europea de Salud de España (EESE): se usan las encuestas de 2014 y 2020.

-   Encuesta de Salud de España (ESdE): se usa la edición de 2023.

Se investigó la posibilidad de utilizar la Encuesta Nacional de Salud (ENSE) de 2017. No se usa por la ausencia de variables importantes para el análisis (las relacionadas con las ausencias en el trabajo, por ejemplo) y por las grandes diferencias en la codificación de algunas de las restantes variables.

El muestreo que se utilizó en la recogida de los datos está diseñado para conseguir la representatividad a nivel nacional y autonómico.

## Variables

### Demográficas

-   `year`: año en que se realizó la encuesta (2014, 2020, 2023).

-   `age`: edad, años.

-   `woman`: 1 si la observación corresponde a una mujer.

-   `partner`: si convive con su cónyuge o pareja de hecho.

-   `nadults`: número de adultos en el hogar.

-   `nchildren`: número de menores de 15 años en el hogar.

-   `hh_size`: número de miembros del hogar.

-   Ficticias para el tipo de hogar:

    | Ficticia | Descripción |
    |--------------------------|----------------------------------------------|
    | `hh_a` | Hogar unipersonal |
    | `hh_b` | Pareja sola |
    | `hh_c` | Pareja con algún hijo menor de 25 años |
    | `hh_d` | Pareja con todos los hijos de 25 o más años |
    | `hh_e` | Padre o madre solo, con algún hijo menor de 25 años |
    | `hh_f` | Padre o madre solo, con todos los hijos de 25 o más años |
    | `hh_g` | Pareja o padre o madre solo, con algún hijo menor de 25 años y otras personas viviendo en el hogar |
    | `hh_h` | Otro tipo de hogar |

-   `ccaa`: comunidad autónoma.

    | Valor | CCAA                        |
    |-------|-----------------------------|
    | AND   | Andalucía                   |
    | ARA   | Aragón                      |
    | AST   | Asturias, Principado de     |
    | BAL   | Balears, Illes              |
    | CAN   | Canarias                    |
    | CNT   | Cantabria                   |
    | CYL   | Castilla y León             |
    | CLM   | Castilla - La Mancha        |
    | CAT   | Cataluña                    |
    | VAL   | Comunitat Valenciana        |
    | EXT   | Extremadura                 |
    | GAL   | Galicia                     |
    | MAD   | Madrid, Comunidad de        |
    | MUR   | Murcia, Región de           |
    | NAV   | Navarra, Comunidad Foral de |
    | PVA   | País Vasco                  |
    | RIO   | Rioja, La                   |
    | CEU   | Ceuta                       |
    | MEL   | Melilla                     |

-   Tamaño del municipio de residencia:

    | Ficticia   | Descripción                                     |
    |------------|-------------------------------------------------|
    | `urb_high` | Más de 50.000 habitantes o capital de provincia |
    | `urb_med`  | Menos de 50.000 y más de 10.000 habitantes      |
    | `urb_low`  | Menos de 10.000 habitantes                      |

-   `native`: 1 si nació en España.

### Estudios

-   Ficticias para el nivel de estudios:

    | Ficticia  | Descripción            |
    |-----------|------------------------|
    | `ed_none` | Primaria no completada |
    | `ed_prim` | Primaria               |
    | `ed_sec`  | Secundaria             |
    | `ed_sup`  | Superior               |

### Situación laboral

-   La actividad laboral se recoge en una serie de variables ficticias:

    | Ficticia     | Descripción                |
    |--------------|----------------------------|
    | `a_working`  | Trabajando                 |
    | `a_unempl`   | Desempleado                |
    | `a_retired`  | Jubilado                   |
    | `a_student`  | Estudiante                 |
    | `a_disabled` | Incapacitado para trabajar |
    | `a_house`    | Labores del hogar          |
    | `a_other`    | Otros                      |

-   Tipo de trabajo:

    | Ficticia     | Descripción                          |
    |--------------|--------------------------------------|
    | `b_public`   | Funcionario                          |
    | `b_temp`     | Temporal                             |
    | `b_perm`     | Indefinido (incluyendo funcionarios) |
    | `b_employer` | Empresario (con empleados)           |
    | `b_self`     | Autónomo (sin empleados)             |
    | `b_other`    | Otros                                |

-   Dedicación:

    | Ficticia     | Descripción       |
    |--------------|-------------------|
    | `b_fulltime` | A tiempo completo |
    | `b_parttime` | A tiempo parcial  |

-   `b_shift`: 1 si trabaja a turnos o la jornada laboral es irregular o variable.

### Estado de salud

-   `c_health_status`: estado de salud autopercibido en los últimos 12 meses:

    | Valor | Descripción |
    |-------|-------------|
    | 1     | Muy bueno   |
    | 2     | Bueno       |
    | 3     | Regular     |
    | 4     | Malo        |
    | 5     | Muy malo    |

-   `c_chronic`: 1 si enfermedad o problema de salud crónicos o de larga duración

-   Grado de limitación durante al menos 6 meses por un problema de salud:

    | Ficticia           | Descripción                  |
    |--------------------|------------------------------|
    | `c_severe_limit`   | Gravemente limitado          |
    | `c_moderate_limit` | Limitado, pero no gravemente |
    | `c_no_limit`       | Nada limitado                |

-   Tipo de problema que causa la limitación:

    | Ficticia           | Descripción |
    |--------------------|-------------|
    | `c_physical_limit` | Físico      |
    | `c_mental_limit`   | Mental      |
    | `c_both_limit`     | Ambos       |

### Ausencias en el trabajo

-   `e_absence`: 1 si se ha ausentado en algún momento de los 12 últimos meses por problemas de salud.

-   `e_absence_days`: número de días de ausencia al trabajo en los últimos 12 meses.

### Actividad física

-   `o_sedentary_work`: 1 si trabaja sentado la mayor parte de la jornada laboral.

-   `o_sedentary_leisure`: 1 si no hace ejercicio y ocupa el tiempo libre de forma casi completamente sedentaria.

### Consumo de tabaco

-   `q_smoker`: 1 si fuma a diario.

-   `q_cigs`: Número de cigarrillos que fuma al día.

### Variables derivadas

-   Índice de masa corporal. Variables ficticias:

    | Ficticia   | Descripción           |
    |------------|-----------------------|
    | `bmi_low`  | Peso insuficiente     |
    | `bmi_med`  | Normopeso y sobrepeso |
    | `bmi_high` | Obesidad              |

-   `alcohol`: consumo medio diario de alcohol (gramos de alcohol).

-   `depress_severity`: Severidad de la sintomatología depresiva:

    | Valor | Descripción         |
    |-------|---------------------|
    | 1     | Ninguna             |
    | 2     | Leve                |
    | 3     | Moderada            |
    | 4     | Moderadamente grave |
    | 5     | Grave               |

-   `depress_major`: 1 si cuadro depresivo mayor.

-   `depress_other`: 1 si otros cuadros depresivos.

-   `depress_none`: 1 si no hay cuadros depresivos.
